USE [master]
GO

/****** Object:  Database [dbWhist]    Script Date: 17-09-2012 13:34:28 ******/
CREATE DATABASE [dbWhist]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbWhist', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MYSQL\MSSQL\DATA\dbWhist.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbWhist_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MYSQL\MSSQL\DATA\dbWhist_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbWhist] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbWhist].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbWhist] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbWhist] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbWhist] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbWhist] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbWhist] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbWhist] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbWhist] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dbWhist] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbWhist] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbWhist] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbWhist] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbWhist] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbWhist] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbWhist] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbWhist] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbWhist] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbWhist] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbWhist] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbWhist] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbWhist] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbWhist] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbWhist] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbWhist] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbWhist] SET RECOVERY FULL 
GO

ALTER DATABASE [dbWhist] SET  MULTI_USER 
GO

ALTER DATABASE [dbWhist] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbWhist] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbWhist] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbWhist] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbWhist] SET  READ_WRITE 
GO

