//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RobotMdl", "RobotRobotRunde", "Robot", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.EntRobot), "RobotRunde", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.EntRobotRundeData), true)]
[assembly: EdmRelationshipAttribute("RobotMdl", "RobotKamp", "Robot", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.EntRobot), "Kamp", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.EntKamp), true)]
[assembly: EdmRelationshipAttribute("RobotMdl", "RobotKamp1", "Robot", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.EntRobot), "Kamp", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.EntKamp), true)]
[assembly: EdmRelationshipAttribute("RobotMdl", "EntKampEntKampRunde", "EntKamp", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication1.EntKamp), "EntKampRunde", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.EntKampRunde), true)]

#endregion

namespace WebApplication1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RobotMdlContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RobotMdlContainer object using the connection string found in the 'RobotMdlContainer' section of the application configuration file.
        /// </summary>
        public RobotMdlContainer() : base("name=RobotMdlContainer", "RobotMdlContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RobotMdlContainer object.
        /// </summary>
        public RobotMdlContainer(string connectionString) : base(connectionString, "RobotMdlContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RobotMdlContainer object.
        /// </summary>
        public RobotMdlContainer(EntityConnection connection) : base(connection, "RobotMdlContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntRobot> EntRobotSet
        {
            get
            {
                if ((_EntRobotSet == null))
                {
                    _EntRobotSet = base.CreateObjectSet<EntRobot>("EntRobotSet");
                }
                return _EntRobotSet;
            }
        }
        private ObjectSet<EntRobot> _EntRobotSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntRobotRundeData> EntRobotRundeDataSet
        {
            get
            {
                if ((_EntRobotRundeDataSet == null))
                {
                    _EntRobotRundeDataSet = base.CreateObjectSet<EntRobotRundeData>("EntRobotRundeDataSet");
                }
                return _EntRobotRundeDataSet;
            }
        }
        private ObjectSet<EntRobotRundeData> _EntRobotRundeDataSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntKamp> EntKampSet
        {
            get
            {
                if ((_EntKampSet == null))
                {
                    _EntKampSet = base.CreateObjectSet<EntKamp>("EntKampSet");
                }
                return _EntKampSet;
            }
        }
        private ObjectSet<EntKamp> _EntKampSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntKampRunde> EntKampRundeSet
        {
            get
            {
                if ((_EntKampRundeSet == null))
                {
                    _EntKampRundeSet = base.CreateObjectSet<EntKampRunde>("EntKampRundeSet");
                }
                return _EntKampRundeSet;
            }
        }
        private ObjectSet<EntKampRunde> _EntKampRundeSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntRobotSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntRobotSet(EntRobot entRobot)
        {
            base.AddObject("EntRobotSet", entRobot);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntRobotRundeDataSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntRobotRundeDataSet(EntRobotRundeData entRobotRundeData)
        {
            base.AddObject("EntRobotRundeDataSet", entRobotRundeData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntKampSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntKampSet(EntKamp entKamp)
        {
            base.AddObject("EntKampSet", entKamp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EntKampRundeSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEntKampRundeSet(EntKampRunde entKampRunde)
        {
            base.AddObject("EntKampRundeSet", entKampRunde);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobotMdl", Name="EntKamp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntKamp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntKamp object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dato">Initial value of the Dato property.</param>
        /// <param name="robotId1">Initial value of the RobotId1 property.</param>
        /// <param name="robotId2">Initial value of the RobotId2 property.</param>
        public static EntKamp CreateEntKamp(global::System.Int32 id, global::System.DateTime dato, global::System.Int32 robotId1, global::System.Int32 robotId2)
        {
            EntKamp entKamp = new EntKamp();
            entKamp.Id = id;
            entKamp.Dato = dato;
            entKamp.RobotId1 = robotId1;
            entKamp.RobotId2 = robotId2;
            return entKamp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Dato
        {
            get
            {
                return _Dato;
            }
            set
            {
                OnDatoChanging(value);
                ReportPropertyChanging("Dato");
                _Dato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dato");
                OnDatoChanged();
            }
        }
        private global::System.DateTime _Dato;
        partial void OnDatoChanging(global::System.DateTime value);
        partial void OnDatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RobotId1
        {
            get
            {
                return _RobotId1;
            }
            set
            {
                OnRobotId1Changing(value);
                ReportPropertyChanging("RobotId1");
                _RobotId1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RobotId1");
                OnRobotId1Changed();
            }
        }
        private global::System.Int32 _RobotId1;
        partial void OnRobotId1Changing(global::System.Int32 value);
        partial void OnRobotId1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RobotId2
        {
            get
            {
                return _RobotId2;
            }
            set
            {
                OnRobotId2Changing(value);
                ReportPropertyChanging("RobotId2");
                _RobotId2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RobotId2");
                OnRobotId2Changed();
            }
        }
        private global::System.Int32 _RobotId2;
        partial void OnRobotId2Changing(global::System.Int32 value);
        partial void OnRobotId2Changed();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobotMdl", "RobotKamp", "Robot")]
        public EntRobot Robot1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntRobot>("RobotMdl.RobotKamp", "Robot").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntRobot>("RobotMdl.RobotKamp", "Robot").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntRobot> Robot1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntRobot>("RobotMdl.RobotKamp", "Robot");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntRobot>("RobotMdl.RobotKamp", "Robot", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobotMdl", "RobotKamp1", "Robot")]
        public EntRobot Robot2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntRobot>("RobotMdl.RobotKamp1", "Robot").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntRobot>("RobotMdl.RobotKamp1", "Robot").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntRobot> Robot2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntRobot>("RobotMdl.RobotKamp1", "Robot");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntRobot>("RobotMdl.RobotKamp1", "Robot", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobotMdl", "EntKampEntKampRunde", "EntKampRunde")]
        public EntityCollection<EntKampRunde> EntKampRunde
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntKampRunde>("RobotMdl.EntKampEntKampRunde", "EntKampRunde");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntKampRunde>("RobotMdl.EntKampEntKampRunde", "EntKampRunde", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobotMdl", Name="EntKampRunde")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntKampRunde : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntKampRunde object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="entKampId">Initial value of the EntKampId property.</param>
        public static EntKampRunde CreateEntKampRunde(global::System.Int32 id, global::System.Int32 entKampId)
        {
            EntKampRunde entKampRunde = new EntKampRunde();
            entKampRunde.Id = id;
            entKampRunde.EntKampId = entKampId;
            return entKampRunde;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rundenr
        {
            get
            {
                return _Rundenr;
            }
            set
            {
                OnRundenrChanging(value);
                ReportPropertyChanging("Rundenr");
                _Rundenr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rundenr");
                OnRundenrChanged();
            }
        }
        private global::System.Int32 _Rundenr = 0;
        partial void OnRundenrChanging(global::System.Int32 value);
        partial void OnRundenrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Udfald
        {
            get
            {
                return _Udfald;
            }
            set
            {
                OnUdfaldChanging(value);
                ReportPropertyChanging("Udfald");
                _Udfald = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Udfald");
                OnUdfaldChanged();
            }
        }
        private global::System.String _Udfald = "X";
        partial void OnUdfaldChanging(global::System.String value);
        partial void OnUdfaldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EntKampId
        {
            get
            {
                return _EntKampId;
            }
            set
            {
                OnEntKampIdChanging(value);
                ReportPropertyChanging("EntKampId");
                _EntKampId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EntKampId");
                OnEntKampIdChanged();
            }
        }
        private global::System.Int32 _EntKampId;
        partial void OnEntKampIdChanging(global::System.Int32 value);
        partial void OnEntKampIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobotMdl", "EntKampEntKampRunde", "EntKamp")]
        public EntKamp Kamp
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntKamp>("RobotMdl.EntKampEntKampRunde", "EntKamp").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntKamp>("RobotMdl.EntKampEntKampRunde", "EntKamp").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntKamp> KampReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntKamp>("RobotMdl.EntKampEntKampRunde", "EntKamp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntKamp>("RobotMdl.EntKampEntKampRunde", "EntKamp", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobotMdl", Name="EntRobot")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntRobot : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntRobot object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static EntRobot CreateEntRobot(global::System.Int32 id)
        {
            EntRobot entRobot = new EntRobot();
            entRobot.Id = id;
            return entRobot;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Navn
        {
            get
            {
                return _Navn;
            }
            set
            {
                OnNavnChanging(value);
                ReportPropertyChanging("Navn");
                _Navn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Navn");
                OnNavnChanged();
            }
        }
        private global::System.String _Navn = "";
        partial void OnNavnChanging(global::System.String value);
        partial void OnNavnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tab
        {
            get
            {
                return _Tab;
            }
            set
            {
                OnTabChanging(value);
                ReportPropertyChanging("Tab");
                _Tab = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tab");
                OnTabChanged();
            }
        }
        private global::System.Int32 _Tab = 0;
        partial void OnTabChanging(global::System.Int32 value);
        partial void OnTabChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sejre
        {
            get
            {
                return _Sejre;
            }
            set
            {
                OnSejreChanging(value);
                ReportPropertyChanging("Sejre");
                _Sejre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sejre");
                OnSejreChanged();
            }
        }
        private global::System.Int32 _Sejre = 0;
        partial void OnSejreChanging(global::System.Int32 value);
        partial void OnSejreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Uafgjort
        {
            get
            {
                return _Uafgjort;
            }
            set
            {
                OnUafgjortChanging(value);
                ReportPropertyChanging("Uafgjort");
                _Uafgjort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Uafgjort");
                OnUafgjortChanged();
            }
        }
        private global::System.Int32 _Uafgjort = 0;
        partial void OnUafgjortChanging(global::System.Int32 value);
        partial void OnUafgjortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Liv
        {
            get
            {
                return _Liv;
            }
            set
            {
                OnLivChanging(value);
                ReportPropertyChanging("Liv");
                _Liv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Liv");
                OnLivChanged();
            }
        }
        private global::System.Int32 _Liv = 0;
        partial void OnLivChanging(global::System.Int32 value);
        partial void OnLivChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobotMdl", "RobotRobotRunde", "RobotRunde")]
        public EntityCollection<EntRobotRundeData> RobotRunde
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntRobotRundeData>("RobotMdl.RobotRobotRunde", "RobotRunde");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntRobotRundeData>("RobotMdl.RobotRobotRunde", "RobotRunde", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobotMdl", "RobotKamp", "Kamp")]
        public EntityCollection<EntKamp> Kamp
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntKamp>("RobotMdl.RobotKamp", "Kamp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntKamp>("RobotMdl.RobotKamp", "Kamp", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RobotMdl", Name="EntRobotRundeData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntRobotRundeData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntRobotRundeData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="robotId">Initial value of the RobotId property.</param>
        public static EntRobotRundeData CreateEntRobotRundeData(global::System.Int32 id, global::System.Int32 robotId)
        {
            EntRobotRundeData entRobotRundeData = new EntRobotRundeData();
            entRobotRundeData.Id = id;
            entRobotRundeData.RobotId = robotId;
            return entRobotRundeData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Skjold
        {
            get
            {
                return _Skjold;
            }
            set
            {
                OnSkjoldChanging(value);
                ReportPropertyChanging("Skjold");
                _Skjold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Skjold");
                OnSkjoldChanged();
            }
        }
        private global::System.Int32 _Skjold = 0;
        partial void OnSkjoldChanging(global::System.Int32 value);
        partial void OnSkjoldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Vaaben
        {
            get
            {
                return _Vaaben;
            }
            set
            {
                OnVaabenChanging(value);
                ReportPropertyChanging("Vaaben");
                _Vaaben = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vaaben");
                OnVaabenChanged();
            }
        }
        private global::System.Int32 _Vaaben = 0;
        partial void OnVaabenChanging(global::System.Int32 value);
        partial void OnVaabenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RobotId
        {
            get
            {
                return _RobotId;
            }
            set
            {
                OnRobotIdChanging(value);
                ReportPropertyChanging("RobotId");
                _RobotId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RobotId");
                OnRobotIdChanged();
            }
        }
        private global::System.Int32 _RobotId;
        partial void OnRobotIdChanging(global::System.Int32 value);
        partial void OnRobotIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RobotMdl", "RobotRobotRunde", "Robot")]
        public EntRobot Robot
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntRobot>("RobotMdl.RobotRobotRunde", "Robot").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntRobot>("RobotMdl.RobotRobotRunde", "Robot").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntRobot> RobotReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntRobot>("RobotMdl.RobotRobotRunde", "Robot");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntRobot>("RobotMdl.RobotRobotRunde", "Robot", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
